// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entity "kururen/entity"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCarByID provides a mock function with given fields: _a0
func (_m *Repository) GetCarByID(_a0 uint) (*entity.Car, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetCarByID")
	}

	var r0 *entity.Car
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*entity.Car, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(uint) *entity.Car); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Car)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCars provides a mock function with given fields:
func (_m *Repository) GetCars() ([]entity.Car, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCars")
	}

	var r0 []entity.Car
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]entity.Car, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []entity.Car); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Car)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCarStatus provides a mock function with given fields: _a0, _a1
func (_m *Repository) UpdateCarStatus(_a0 uint, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCarStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
